server:
  port: 5634
spring:
  application:
    name: db-last-modify-transfer
  redis:
    host: 172.16.10.199
    port: 6379
    password:
    timeout: 0
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 8
      minIdle: 0

  data:
    mongodb:
      authentication-database: tara
      repositories:
        enabled: true
      uri: mongodb://172.16.10.199:27017/cancal_lastmodify



# UI显示日志
logging:
  file: ./logs/${spring.application.name}.log
  level:
    root: debug
    rx: warn
    io.undertow: warn
    org.springframework: warn
    org.apache: warn
    com.netflix: warn
    de.codecentric: warn
    com.sun.jersey: warn
    org.I0Itec: warn
    javax.activation: warn
    com.sun: warn
    javax: warn
    sun.rmi: warn

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_REPLICAS_LIST:172.16.10.196:1111}



sgsl:
  custom:
    canal:
      config:
        dstination: example
        simple-properties:
          canal-server-ip: ${CANAL_SERVER_IP:172.16.10.194}
          canal-server-port: ${CANAL_SERVER_PORT:11111}
        user-id-column-names:
          - user_id
        db-subjections:
          -
            db-name: foodseetest
            service-name: app-server
          -
            db-name: foodsee_development
            service-name: app-server

