server:
  port: 3506
spring:
  application:
    name: dingtalk-error-notify-example

# UI显示日志
logging:
  file: ./logs/${spring.application.name}.log
  level:
    root: debug
    rx: warn
    io.undertow: warn
    org.springframework: warn
    org.apache: warn
    com.netflix: warn
    de.codecentric: warn
    com.sun.jersey: warn
    org.I0Itec: warn
    javax.activation: warn
    com.sun: warn
    javax: warn
    sun.rmi: warn

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_REPLICAS_LIST}


sgsl:
    custom:
      lastmodify:
        metadata:
          config:
            enabled: true
            last-modify-meta-data:
              -
                api-name: /dingtalk-test/test/{id}
                table-names:
                  - T_GOODS_STANDARD
                  - T_GOODS_INFO
                  - T_UNIT_INFO
                is-user: false

              -
                api-name: /dingtalk-test/test
                table-names:
                  - T_GOODS_STANDARD
                  - T_GOODS_INFO
                  - T_UNIT_INFO
                is-user: true



management:
  security:
    enabled: false
